const eliminar = [
'Datos del Imputado (septuagésimo séptimo)', 
'Datos del Imputado (septuagésimo tercero)', 
'Datos del Imputado (septuagésimo)', 
'Datos del Imputado (sexagésimo cuarto)', 
'Datos del Imputado (sexagésimo noveno)', 
'Datos del Imputado (sexagésimo octavo)', 
'Datos del Imputado (sexagésimo primero)', 
'Datos del Imputado (sexagésimo quinto)', 
'Datos del Imputado (sexagésimo segundo)', 
'Datos del Imputado (sexagésimo sexto)', 
'Datos de la víctima u ofendido (Octogésimo cuestionario)', 
'Datos de la víctima u ofendido (Octogésimo primero cuestionario)', 
'Datos de la víctima u ofendido (Octogésimo segundo cuestionario)', 
'Datos de la víctima u ofendido (centécimo cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo noveno cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo octavo cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo primero cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo quinto cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo segundo cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo sexto cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (cuadragésimo tercero cuestionario)', 
'Datos de la víctima u ofendido (décimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (décimo noveno cuestionario)', 
'Datos de la víctima u ofendido (décimo octavo cuestionario)', 
'Datos de la víctima u ofendido (décimo primero cuestionario)', 
'Datos de la víctima u ofendido (décimo quinto cuestionario)', 
'Datos de la víctima u ofendido (décimo segundo cuestionario)', 
'Datos de la víctima u ofendido (décimo sexto cuestionario)', 
'Datos de la víctima u ofendido (décimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (décimo tercero cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo noveno cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo octavo cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo primero cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo quinto cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo segundo cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (nonagésimo tercero cuestionario)', 
'Datos de la víctima u ofendido (octogésimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (octogésimo noveno cuestionario)', 
'Datos de la víctima u ofendido (octogésimo octavo cuestionario)', 
'Datos de la víctima u ofendido (octogésimo quinto cuestionario)', 
'Datos de la víctima u ofendido (octogésimo sexto cuestionario)', 
'Datos de la víctima u ofendido (octogésimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (octogésimo tercero cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo noveno cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo octavo cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo primero cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo quinto cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo segundo cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo sexto cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (quincuagésimo tercero cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo noveno cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo octavo cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo primero cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo quinto cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo segundo cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo sexto cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (septuagésimo tercero cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo noveno cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo octavo cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo primero cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo quinto cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo segundo cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo sexto cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (sexagésimo tercero cuestionario)', 
'Datos de la víctima u ofendido (trigésimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (trigésimo cuestionario)', 
'Datos de la víctima u ofendido (trigésimo noveno cuestionario)', 
'Datos de la víctima u ofendido (trigésimo octavo cuestionario)', 
'Datos de la víctima u ofendido (trigésimo primero cuestionario)', 
'Datos de la víctima u ofendido (trigésimo quinto cuestionario)', 
'Datos de la víctima u ofendido (trigésimo segundo cuestionario)', 
'Datos de la víctima u ofendido (trigésimo sexto cuestionario)', 
'Datos de la víctima u ofendido (trigésimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (trigésimo tercero cuestionario)', 
'Datos de la víctima u ofendido (vigésimo cuarto cuestionario)', 
'Datos de la víctima u ofendido (vigésimo cuestionario)', 
'Datos de la víctima u ofendido (vigésimo noveno cuestionario)', 
'Datos de la víctima u ofendido (vigésimo octavo cuestionario)', 
'Datos de la víctima u ofendido (vigésimo primero cuestionario)', 
'Datos de la víctima u ofendido (vigésimo quinto cuestionario)', 
'Datos de la víctima u ofendido (vigésimo segundo cuestionario)', 
'Datos de la víctima u ofendido (vigésimo sexto cuestionario)', 
'Datos de la víctima u ofendido (vigésimo séptimo cuestionario)', 
'Datos de la víctima u ofendido (vigésimo tercero cuestionario)', 
'Datos del Imputado (centésimo)', 
'Datos del Imputado (cuadragésimo cuarto)', 
'Datos del Imputado (cuadragésimo noveno)', 
'Datos del Imputado (cuadragésimo octavo)', 
'Datos del Imputado (cuadragésimo primero)', 
'Datos del Imputado (cuadragésimo quinto)', 
'Datos del Imputado (cuadragésimo segundo)', 
'Datos del Imputado (cuadragésimo sexto)', 
'Datos del Imputado (cuadragésimo séptimo)', 
'Datos del Imputado (cuadragésimo tercero)', 
'Datos del Imputado (cuadragésimo)', 
'Datos del Imputado (décimo cuarto)', 
'Datos del Imputado (décimo noveno)', 
'Datos del Imputado (décimo octavo)', 
'Datos del Imputado (décimo primero)', 
'Datos del Imputado (décimo quinto)', 
'Datos del Imputado (décimo segundo)', 
'Datos del Imputado (décimo sexto)', 
'Datos del Imputado (décimo séptimo)', 
'Datos del Imputado (décimo tercero)', 
'Datos del Imputado (nonagésimo cuarto)', 
'Datos del Imputado (nonagésimo noveno)', 
'Datos del Imputado (nonagésimo octavo)', 
'Datos del Imputado (nonagésimo primero)', 
'Datos del Imputado (nonagésimo quinto)', 
'Datos del Imputado (nonagésimo segundo)', 
'Datos del Imputado (nonagésimo septimo)', 
'Datos del Imputado (nonagésimo sexto)', 
'Datos del Imputado (nonagésimo tercero)', 
'Datos del Imputado (nonagésimo)', 
'Datos del Imputado (octogésimo cuarto)', 
'Datos del Imputado (octogésimo noveno)', 
'Datos del Imputado (octogésimo octavo)', 
'Datos del Imputado (octogésimo primero)', 
'Datos del Imputado (octogésimo quinto)', 
'Datos del Imputado (octogésimo segundo)', 
'Datos del Imputado (octogésimo sexto)', 
'Datos del Imputado (octogésimo séptimo)', 
'Datos del Imputado (octogésimo tercero)', 
'Datos del Imputado (octogésimo)', 
'Datos del Imputado (quincuagésimo cuarto)', 
'Datos del Imputado (quincuagésimo noveno)', 
'Datos del Imputado (quincuagésimo octavo)', 
'Datos del Imputado (quincuagésimo primero)', 
'Datos del Imputado (quincuagésimo quinto)', 
'Datos del Imputado (quincuagésimo segundo)', 
'Datos del Imputado (quincuagésimo séptimo)', 
'Datos del Imputado (quincuagésimo tercer)', 
'Datos del Imputado (quincuagésimo)', 
'Datos del Imputado (septuagésimo cuarto)', 
'Datos del Imputado (septuagésimo noveno)', 
'Datos del Imputado (septuagésimo octavo)', 
'Datos del Imputado (septuagésimo primero)', 
'Datos del Imputado (septuagésimo quinto)', 
'Datos del Imputado (septuagésimo segundo)', 
'Datos del Imputado (septuagésimo sexto)', 
'Datos del Imputado (septuagésimo sexto) (Copiar)', 
'Datos del Imputado (sexagésimo séptimo)', 
'Datos del Imputado (sexagésimo tercero)', 
'Datos del Imputado (sexagésimo)', 
'Datos del Imputado (trigésimo cuarto)', 
'Datos del Imputado (trigésimo noveno)', 
'Datos del Imputado (trigésimo octavo)', 
'Datos del Imputado (trigésimo primero)', 
'Datos del Imputado (trigésimo quinto)', 
'Datos del Imputado (trigésimo segundo)', 
'Datos del Imputado (trigésimo sexto)', 
'Datos del Imputado (trigésimo séptimo)', 
'Datos del Imputado (trigésimo tercero)', 
'Datos del Imputado (trigésimo)', 
'Datos del Imputado (vigésimo cuarto)', 
'Datos del Imputado (vigésimo noveno)', 
'Datos del Imputado (vigésimo octavo)', 
'Datos del Imputado (vigésimo primer)', 
'Datos del Imputado (vigésimo quinto)', 
'Datos del Imputado (vigésimo segundo)', 
'Datos del Imputado (vigésimo sexto)', 
'Datos del Imputado (vigésimo séptimo)', 
'Datos del Imputado (vigésimo tercer)', 
'Datos del Imputado (vigésimo)']


describe('Inicia el tramite luego lo cancela', () => {
    

    beforeEach(() => {
        cy.session('sesionAdmin', () => {
            cy.visit(); // reemplazar con la URL de inicio de sesión
            cy.get('input[placeholder="Nombre de usuario o correo electrónico."]').type();  // reemplazar con el usuario administrador
            cy.get('input[placeholder="Escribe la contraseña"]').type(); // reemplazar con la contraseña del usuario administrador
            cy.contains('button', 'Ingresar').click();
            cy.wait(10000);
        });

    })

    eliminar.forEach((form) => {
        it(form, () => {
            cy.visit('https://sandbox.nilo.cjj.gob.mx/forms/71/index', { log: false });

            cy.get('input[placeholder="Buscar"][type="search"]', { log: false })
                .type(form + '{enter}', { log: false });

            cy.wait(10000);

            // Interceptar confirm
            cy.on('window:confirm', () => true); // Acepta el confirm

            cy.contains('td', form, { log: false }).should('exist').and('be.visible')
                .closest('tr')
                .find('i[data-original-title="Eliminar"]', { log: false })
                .parent().click();
            cy.contains('button', 'Aceptar').click({ force: true });
        });
    });

})